### ISSUE TITLE
VS 2019

### ISSUE THREAD

**Issue by midnight-sun** [nHydrate/nHydrate#51]
Are there plans to port this extension and make it 2019 compatible?

Please advise,

Steve

**Comment by mtgibbs** [comment]
Most of the time the plugin is pretty compatible already, we probably just need to update the compatibility list. Does it not work or let you install via .vsix?

**Comment by midnight-sun** [comment]
The plugin does not appear in the marketplace within Visual Studio.   Attempting to install it with the VSIX failed as "Not installable on any currently installed products"

> 2019-10-17 5:00:29 PM - Initializing Install...
2019-10-17 5:00:30 PM - Extension Details...
2019-10-17 5:00:30 PM - 	Identifier         : 36220dab-63c7-4daa-860c-fc548bf4d5d3
2019-10-17 5:00:30 PM - 	Name               : nHydrate ORM Modeler
2019-10-17 5:00:30 PM - 	Author             : nHydrate.org
2019-10-17 5:00:30 PM - 	Version            : 6.0.0.222
2019-10-17 5:00:30 PM - 	Description        : This is the nHydrate Visual Modeler
2019-10-17 5:00:30 PM - 	Locale             : en-US
2019-10-17 5:00:30 PM - 	MoreInfoURL        : 
2019-10-17 5:00:30 PM - 	InstalledByMSI     : False
2019-10-17 5:00:30 PM - 	SupportedFrameworkVersionRange : [4.5,)
2019-10-17 5:00:30 PM - 
2019-10-17 5:00:30 PM - 	SignatureState     : Unsigned
2019-10-17 5:00:30 PM - 	Supported Products : 
2019-10-17 5:00:30 PM - 		Microsoft.VisualStudio.Community
2019-10-17 5:00:30 PM - 			Version : [12.0,15.0]
2019-10-17 5:00:30 PM - 
2019-10-17 5:00:30 PM - 	References         : 
2019-10-17 5:00:30 PM - 	Prerequisites      : 
2019-10-17 5:00:30 PM - 		-------------------------------------------------------
2019-10-17 5:00:30 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2019-10-17 5:00:30 PM - 		Name         : Visual Studio core editor
2019-10-17 5:00:30 PM - 		Version      : [12.0,16.0)
2019-10-17 5:00:30 PM - 
2019-10-17 5:00:30 PM - Signature Details...
2019-10-17 5:00:30 PM - 	Extension is not signed.
2019-10-17 5:00:30 PM - 
2019-10-17 5:00:30 PM - Searching for applicable products...
2019-10-17 5:00:30 PM - Found installed product - Global Location
2019-10-17 5:00:30 PM - Found installed product - Visual Studio Professional 2019
2019-10-17 5:00:30 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by gravbox** [comment]
The component has been recompiled to include VS 2019 and version updated. It is in the gallery now.
